# Project information
site_name: SAFE Documentation
site_description: Documentation for SAFE
site_author: SAFE Stack
site_url: http://safe-stack.github.io/docs/

# Repository
repo_name: SAFE-Stack/docs
repo_url: https://github.com/SAFE-Stack/docs
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'light blue'
    accent: 'indigo'
  logo: img/safe_favicon.png

markdown_extensions:
  - codehilite

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/SAFE-Stack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/safe_stack
    - icon: fontawesome/solid/globe
      link: https://safe-stack.github.io/

nav:
- Home: 'index.md'
- Introduction: 'intro.md'
- Quick Start: 'quickstart.md'
- SAFE Stack Overview: 'overview.md'
- Components of SAFE:
  - Learn about Saturn : 'component-saturn.md'
  - Learn about Azure : 'component-azure.md'
  - Learn about Fable : 'component-fable.md'
  - Learn about Elmish : 'component-elmish.md'
- The SAFE Template:
  - Overview: 'template-overview.md'
  - The FAKE script: 'template-fake.md'
- Features of SAFE:
  - Client / Server Sharing:
    - Sharing Overview : 'feature-clientserver.md'
    - Sharing Types and Code : 'feature-clientserver-basics.md'
    - Messaging using HTTP : 'feature-clientserver-http.md'
    - Messaging with Protocols : 'feature-clientserver-remoting.md'
    - Stateful Messaging through Bridge : 'feature-clientserver-bridge.md'
    - Serialization in SAFE : 'feature-clientserver-serialization.md'
  - Full Stack Debugging: 'feature-debugging.md'
  - Server Side Rendering : 'feature-ssr.md'
  - Hot Module Replacement : 'feature-hmr.md'
  - Working with Azure functions : 'feature-azurefunctions.md'
- How do I...:
  - Create a new Recipe: 'recipes/template.md'
  - Build:
    - Remove FAKE from my project: 'recipes/build/remove-fake.md'
    - Add a build automation: 'recipes/build/add-build-script.md'
    - Package my SAFE app for deployment: 'recipes/build/bundle-app.md'
    - Support older browsers: 'recipes/build/support-older-browsers.md'
  - Client / Server:
    - Add support for Fable Remoting: 'recipes/client-server/fable-remoting.md'
    - Perform roundtrips with MVU: 'recipes/client-server/mvu-roundtrip.md'
    - Get data from the server: 'recipes/client-server/messaging.md'
    - Post data to the server: 'recipes/client-server/messaging-post.md'
    - Handle server errors on the client: 'recipes/client-server/server-errors-on-client.md'
    - Share code between the client and the server: 'recipes/client-server/share-code.md'
    - Use Giraffe instead of Saturn: "recipes/client-server/saturn-to-giraffe.md"
  - Data:
    - Quickly add a database: 'recipes/storage/use-litedb.md'
  - UI:
    - Add FontAwesome support: 'recipes/ui/add-fontawesome.md'
    - Add Stylesheet support: 'recipes/ui/add-style.md'
    - Add Bulma support: 'recipes/ui/add-bulma.md'
    - Use different Bulma Themes: 'recipes/ui/use-different-bulma-themes.md'
    - Add Feliz support: 'recipes/ui/add-feliz.md'
    - Migrate from a CDN stylesheet to an NPM package: 'recipes/ui/cdn-to-npm.md'
  - Javascript:
    - Import a JavaScript module: 'recipes/javascript/import-js-module.md'
    - Add Support for a Third Party React Library: 'recipes/javascript/third-party-react-package.md'
  - Dev / Test:
    - Use hot reload: 'recipes/developing-and-testing/using-hot-reload.md'
    - Testing the Client: 'recipes/developing-and-testing/testing-the-client.md'
    - Testing the Server: 'recipes/developing-and-testing/testing-the-server.md'
  - Package Management:
    - Add an NPM package to the Client: 'recipes/package-management/add-npm-package-to-client.md'
    - Add a NuGet package to the Server: 'recipes/package-management/add-nuget-package-to-server.md'
    - Add a Nuget package to the Client: 'recipes/package-management/add-nuget-package-to-client.md'
    - Migrate to Paket from NuGet: 'recipes/package-management/migrate-to-paket.md'
    - Migrate to Yarn from NPM: 'recipes/package-management/migrate-to-yarn.md'
    - Sync NuGet and NPM Packages: 'recipes/package-management/sync-nuget-and-npm-packages.md'

- FAQs:
  - Moving from dev to prod : 'faq-build.md'
  - Troubleshooting : 'faq-troubleshooting.md'
- Learning Resources: 'learning.md'
- News: 'news.md'
- Events: 'events.md'
- Support: 'support.md'
- Testimonials: 'testimonials.md'
- Legacy SAFE Template (v1):
  - Overview: 'legacy-template-overview.md'
  - Run and Build the app: 'legacy-template-fake.md'
  - Deploy to Docker: 'legacy-template-docker.md'
  - Deploy to App Service: 'legacy-template-appservice.md'
  - Deploy to Google Cloud AppEngine: 'legacy-template-gcp-appengine.md'
  - Deploy to Google Cloud Kubernetes Engine: 'legacy-template-gcp-kubernetes.md'
  - Deploy to Heroku: 'legacy-template-heroku.md'
  - Deploy to IIS: 'legacy-template-iis.md'
  - Application Insights Integration: 'legacy-template-azure-ai.md'
  - Registering with Azure: 'legacy-template-azure-registration.md'
  - Registering with Google Cloud: 'legacy-template-google-cloud.md'