# Project information
site_name: SAFE Documentation
site_description: Documentation for SAFE
site_author: SAFE Stack
site_url: http://safe-stack.github.io/docs/

# Repository
repo_name: SAFE-Stack/docs
repo_url: https://github.com/SAFE-Stack/docs
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'orange'
    accent: 'blue'

markdown_extensions:
  - codehilite

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/SAFE-Stack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/safe_stack
    - icon: fontawesome/solid/globe
      link: https://safe-stack.github.io/

nav:
- Home: 'index.md'
- Introduction: 'intro.md'
- Quick Start: 'quickstart.md'
- SAFE Stack Overview: 'overview.md'
- Components of SAFE:
  - Learn about Saturn : 'component-saturn.md'
  - Learn about Azure : 'component-azure.md'
  - Learn about Fable : 'component-fable.md'
  - Learn about Elmish : 'component-elmish.md'
- The SAFE Template:
  - Overview: 'template-overview.md'
  - Run and Build the app: 'template-fake.md'
  - Deployment Options:
    - Deploy to Docker: 'template-docker.md'
    - Deploy to App Service: 'template-appservice.md'
    - Deploy to Google Cloud AppEngine: 'template-gcp-appengine.md'
    - Deploy to Google Cloud Kubernetes Engine: 'template-gcp-kubernetes.md'
    - Deploy to Heroku: 'template-heroku.md'
    - Deploy to IIS: 'template-iis.md'
    - Application Insights Integration: 'template-azure-ai.md'
    - Registering with Azure: 'template-azure-registration.md'
    - Registering with Google Cloud: 'template-google-cloud.md'
- Features of SAFE:
  - Client / Server Sharing:
    - Sharing Overview : 'feature-clientserver.md'
    - Sharing Types and Code : 'feature-clientserver-basics.md'
    - Messaging using HTTP : 'feature-clientserver-http.md'
    - Messaging with Protocols : 'feature-clientserver-remoting.md'
    - Stateful Messaging through Bridge : 'feature-clientserver-bridge.md'
    - Serialization in SAFE : 'feature-clientserver-serialization.md'
  - Full Stack Debugging: 'feature-debugging.md'
  - Server Side Rendering : 'feature-ssr.md'
  - Hot Module Replacement : 'feature-hmr.md'
  - Working with Azure functions : 'feature-azurefunctions.md'
- How do I...:
  - Create a new Recipe: 'recipes/template.md'
  - Hosting:
    - Bundle my SAFE app: 'recipes/hosting/bundle-app.md'
  - UI:
    - Add Bulma: 'recipes/ui/add-bulma.md'
    - Add Feliz: 'recipes/ui/add-feliz.md'
  - Package Management:
    - Add an NPM package to the Client: 'recipes/package-management/add-npm-package-to-client.md'
    - Migrate to Paket from NuGet: 'recipes/package-management/migrate-to-paket.md'
- FAQs:
  - Choosing your web server : 'faq-server.md'
  - Moving from dev to prod : 'faq-build.md'
  - Troubleshooting : 'faq-troubleshooting.md'
- Learning Resources: 'learning.md'
- News: 'news.md'
- Events: 'events.md'
- Support: 'support.md'
- Testimonials: 'testimonials.md'
